# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    core.products_manager:
        class: AppBundle\Managers\ProductsManager
        arguments:
            - '@doctrine.orm.entity_manager'
